In [1]:
import numpy as np
import pandas as pd

data = pd.Series(np.random.randn(9),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                       [1, 2, 3, 1, 2, 3, 1, 2, 3]])
data

a  1    0.259772
   2    0.061540
   3    1.215948
b  1   -0.449339
   2   -1.193064
c  3    0.160231
   1    0.032246
d  2    0.377001
   3    1.161595
dtype: float64

In [ ]:
data1 = data.unstack()   # 寬資料
data1

          1         2         3
a  0.259772  0.061540  1.215948
b -0.449339 -1.193064       NaN
c  0.032246       NaN  0.160231
d       NaN  0.377001  1.161595

In [ ]:
data1.stack()   # 長資料

a  1    0.259772
   2    0.061540
   3    1.215948
b  1   -0.449339
   2   -1.193064
   3         NaN
c  1    0.032246
   2         NaN
   3    0.160231
d  1         NaN
   2    0.377001
   3    1.161595
dtype: float64

In [8]:
import numpy as np
import pandas as pd

frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                    index=[['a','a','b','b'],[1, 2, 1, 2]],
                    columns=[['台北','台北','台中'],['Green','Red','Green']])
frame.index.names = ['key1', 'key2']
frame.columns.names = ['縣市','顏色']
frame

縣市           台北        台中
顏色        Green Red Green
key1 key2
a    1        0   1     2
     2        3   4     5
b    1        6   7     8
     2        9  10    11

In [9]:
frame1 = frame.stack(['顏色','縣市'])
frame1

key1  key2  顏色     縣市
a     1     Green  台北     0
            Red    台北     1
            Green  台中     2
      2     Green  台北     3
            Red    台北     4
            Green  台中     5
b     1     Green  台北     6
            Red    台北     7
            Green  台中     8
      2     Green  台北     9
            Red    台北    10
            Green  台中    11
dtype: int64

In [10]:
frame1.unstack('key1')

key1           a   b
key2 顏色    縣市
1    Green 台中  2   8
           台北  0   6
     Red   台北  1   7
2    Green 台中  5  11
           台北  3   9
     Red   台北  4  10

In [11]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'key1':['a', 'a', 'b', 'b', 'a'],
                  'key2':['one', 'two', 'one', 'two', 'one'],
                  'data1': np.random.randn(5),
                  'data2':np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one -0.861980  0.095747
1    a  two -1.221540 -0.025283
2    b  one  1.055095 -1.228768
3    b  two -0.072820 -0.187908
4    a  one -0.884676  1.337550

In [12]:
df.groupby('key1').sum()

           key2     data1     data2
key1
a     onetwoone -2.968196  1.408014
b        onetwo  0.982275 -1.416676