In [2]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df.groupby("性別")[['國文', '英文', '數學', '地理', '歷史']].agg('mean')

           國文         英文         數學         地理         歷史
性別
女   69.227273  76.272727  74.272727  74.590909  76.454545
男   72.821429  74.821429  72.428571  75.000000  76.714286

In [4]:
scores_df

    國文   英文   數學  地理   歷史   姓名 性別
1   70   93   71  99   60  劉怡君  女
2   66   66   72  60   81  黃詩涵  女
3   52   71   89  89   96  郭柏翰  男
4   69   57   94  98   83  王家豪  男
5   86   89   70  73   96  鄭詩涵  女
6   57  100   55  79   94  鄭怡君  女
7   77   75   62  60   52  蔡詩涵  女
8   84   70   63  53   92  李柏翰  男
9   62   57   69  65   80  賴怡君  女
10  51   54   84  97   70  楊欣怡  女
11  93   71  100  67   94  吳冠宇  男
12  69   98   78  62   59  許詩涵  女
13  59   82   52  94   50  廖志明  男
14  78   50   87  63   75  張詩涵  女
15  89   53   94  67   77  許冠宇  男
16  93   83   63  86   76  曾俊傑  男
17  66   64   70  63   82  張志明  男
18  74   83   85  83   61  鄭冠宇  男
19  89   52   73  86   88  邱佳蓉  女
20  50   80   58  83   99  許怡君  女
21  83   52   62  94   74  邱柏翰  男
22  98   97   72  94   54  蔡志明  男
23  73   91   75  58   53  王志明  男
24  61   99   83  98   94  王怡君  女
25  58   85   56  65   78  洪冠宇  男
26  78  100   52  67   88  蔡欣怡  女
27  69   99   66  61   98  洪柏翰  男
28  68   54   69  68   99  林冠宇  男
29  53   84   53  69   93  楊雅婷  女
30  66   63  100  75   74  謝怡君  女
31  91   78   85  53   99  曾志明  男
32  56   89   77  74   57  謝柏翰  男
33  64   82   65  73   68  黃柏翰  男
34  73   69   64  90  100  劉家豪  男
35  80   68   63  96   67  徐怡君  女
36  95   73   73  89   70  曾柏翰  男
37  54   67   65  69   72  楊柏翰  男
38  60   62   56  72   69  許柏翰  男
39  53   65   80  92   63  廖冠宇  男
40  86   82   91  60   98  廖怡君  女
41  68   96   86  51   74  陳柏翰  男
42  54   73   62  62   70  劉詩涵  女
43  77   86   78  88   62  陳怡君  女
44  55   73   89  50   80  張怡君  女
45  81   74   97  53   51  李雅婷  女
46  77   81   87  69   97  賴俊傑  男
47  62   81   55  75   71  林柏翰  男
48  83   75   64  75   84  劉志明  男
49  77   62   87  96   51  邱欣怡  女
50  75   65   61  78   57  曾家豪  男

In [5]:
# 依性別分組，計算各科平均分數
subjects = ['國文', '英文', '數學', '地理', '歷史']
gender_group = scores_df.groupby('性別')[subjects].mean().round(2)
gender_group

       國文     英文     數學     地理     歷史
性別
女   69.23  76.27  74.27  74.59  76.45
男   72.82  74.82  72.43  75.00  76.71

In [6]:
# 計算學生總分，並分成三個分數階級
scores_df['學生總分'] = scores_df[subjects].sum(axis=1)
scores_df['分數階級'] = pd.cut(
    scores_df['學生總分'],
    bins=[0, 300, 400, float('inf')],
    labels=['低分區', '一般區', '高分區'],
    right=False
)
scores_df

    國文   英文   數學  地理   歷史   姓名 性別  學生總分 分數階級
1   70   93   71  99   60  劉怡君  女   393  一般區
2   66   66   72  60   81  黃詩涵  女   345  一般區
3   52   71   89  89   96  郭柏翰  男   397  一般區
4   69   57   94  98   83  王家豪  男   401  高分區
5   86   89   70  73   96  鄭詩涵  女   414  高分區
6   57  100   55  79   94  鄭怡君  女   385  一般區
7   77   75   62  60   52  蔡詩涵  女   326  一般區
8   84   70   63  53   92  李柏翰  男   362  一般區
9   62   57   69  65   80  賴怡君  女   333  一般區
10  51   54   84  97   70  楊欣怡  女   356  一般區
11  93   71  100  67   94  吳冠宇  男   425  高分區
12  69   98   78  62   59  許詩涵  女   366  一般區
13  59   82   52  94   50  廖志明  男   337  一般區
14  78   50   87  63   75  張詩涵  女   353  一般區
15  89   53   94  67   77  許冠宇  男   380  一般區
16  93   83   63  86   76  曾俊傑  男   401  高分區
17  66   64   70  63   82  張志明  男   345  一般區
18  74   83   85  83   61  鄭冠宇  男   386  一般區
19  89   52   73  86   88  邱佳蓉  女   388  一般區
20  50   80   58  83   99  許怡君  女   370  一般區
21  83   52   62  94   74  邱柏翰  男   365  一般區
22  98   97   72  94   54  蔡志明  男   415  高分區
23  73   91   75  58   53  王志明  男   350  一般區
24  61   99   83  98   94  王怡君  女   435  高分區
25  58   85   56  65   78  洪冠宇  男   342  一般區
26  78  100   52  67   88  蔡欣怡  女   385  一般區
27  69   99   66  61   98  洪柏翰  男   393  一般區
28  68   54   69  68   99  林冠宇  男   358  一般區
29  53   84   53  69   93  楊雅婷  女   352  一般區
30  66   63  100  75   74  謝怡君  女   378  一般區
31  91   78   85  53   99  曾志明  男   406  高分區
32  56   89   77  74   57  謝柏翰  男   353  一般區
33  64   82   65  73   68  黃柏翰  男   352  一般區
34  73   69   64  90  100  劉家豪  男   396  一般區
35  80   68   63  96   67  徐怡君  女   374  一般區
36  95   73   73  89   70  曾柏翰  男   400  高分區
37  54   67   65  69   72  楊柏翰  男   327  一般區
38  60   62   56  72   69  許柏翰  男   319  一般區
39  53   65   80  92   63  廖冠宇  男   353  一般區
40  86   82   91  60   98  廖怡君  女   417  高分區
41  68   96   86  51   74  陳柏翰  男   375  一般區
42  54   73   62  62   70  劉詩涵  女   321  一般區
43  77   86   78  88   62  陳怡君  女   391  一般區
44  55   73   89  50   80  張怡君  女   347  一般區
45  81   74   97  53   51  李雅婷  女   356  一般區
46  77   81   87  69   97  賴俊傑  男   411  高分區
47  62   81   55  75   71  林柏翰  男   344  一般區
48  83   75   64  75   84  劉志明  男   381  一般區
49  77   62   87  96   51  邱欣怡  女   373  一般區
50  75   65   61  78   57  曾家豪  男   336  一般區

In [7]:
# 依分數階級分組，統計學生人數與平均總分
score_level_group = (
    scores_df.groupby('分數階級', observed=False)
    .agg(學生人數=('姓名', 'count'), 平均總分=('學生總分', 'mean'))
    .round(2)
    .sort_index(ascending=False)
)
score_level_group

      學生人數    平均總分
分數階級
高分區     10  412.50
一般區     40  361.08
低分區      0     NaN