In [2]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))
scores_df.T

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
國文,98,75,80,56,66,74,99,90,88,94,...,85,87,96,87,70,75,50,80,90,79
英文,67,65,70,83,100,71,65,76,73,85,...,50,76,71,89,67,76,98,86,50,72
數學,62,52,91,91,59,72,71,53,85,97,...,81,99,99,83,100,98,82,96,53,52
地理,75,91,67,67,69,65,95,79,84,74,...,63,50,57,82,60,75,50,84,58,100
歷史,87,94,83,87,70,81,64,62,76,51,...,52,72,93,96,74,53,61,62,71,70

In [3]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
scores_df

     姓名 性別   國文   英文   數學  地理   歷史
1   劉怡君  女   68   91   53  52   90
2   黃詩涵  女   56   86   94  79   71
3   郭柏翰  男   75   79   83  70   55
4   王家豪  男   55   95   95  93   86
5   鄭詩涵  女   54   74   71  91   96
6   鄭怡君  女   93   76   50  68   69
7   蔡詩涵  女   61   58   90  64   82
8   李柏翰  男   65   98   76  50   95
9   賴怡君  女   89   82   91  66  100
10  楊欣怡  女   75   81   57  95   61
11  吳冠宇  男   77   78   70  52   69
12  許詩涵  女   92   94   89  61   54
13  廖志明  男   74   70   79  86   50
14  張詩涵  女   83   93   86  70   92
15  許冠宇  男   88   78   53  73   98
16  曾俊傑  男   72   72   54  52   78
17  張志明  男   84   80   71  73   58
18  鄭冠宇  男   79  100   68  54   57
19  邱佳蓉  女   92   93   83  90   74
20  許怡君  女   79   61   98  50   63
21  邱柏翰  男   93   87   58  64   55
22  蔡志明  男   94   51   80  92   68
23  王志明  男   68   57   78  91   81
24  王怡君  女   70   55   80  57   72
25  洪冠宇  男   64   94  100  57   91
26  蔡欣怡  女   63   76   90  84   73
27  洪柏翰  男   73  100   63  96   92
28  林冠宇  男   64   66   80  91   89
29  楊雅婷  女   66   99   87  75   83
30  謝怡君  女   55   84   77  78   65
31  曾志明  男   89   71   74  93   95
32  謝柏翰  男   89   62   77  59   58
33  黃柏翰  男   75   55   58  57   93
34  劉家豪  男   97   76   83  84   82
35  徐怡君  女   65   54   58  86   68
36  曾柏翰  男   56   92   67  92   54
37  楊柏翰  男   50   91   85  72   70
38  許柏翰  男   95   89   59  83   67
39  廖冠宇  男   81   98   50  86   68
40  廖怡君  女   98   89   68  55   72
41  陳柏翰  男   61   60   79  95   90
42  劉詩涵  女  100   99   82  62   62
43  陳怡君  女   76   69   65  53   62
44  張怡君  女   89   86   80  63   53
45  李雅婷  女   81   94   58  93   69
46  賴俊傑  男   51   64   61  57   95
47  林柏翰  男   58   83   53  70   50
48  劉志明  男   82   64   82  80   76
49  邱欣怡  女   63   69   70  63   97
50  曾家豪  男   91   92   74  98   55

In [4]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
# 選取欄
scores_df[['姓名','國文']]
# 選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   鄭怡君  女  65  94  85  91  64
7   蔡詩涵  女  80  63  69  53  69
8   李柏翰  男  87  98  73  61  59
9   賴怡君  女  99  64  64  71  68
10  楊欣怡  女  54  92  99  97  78

In [5]:
scores_df[scores_df['姓名'] == '楊欣怡']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60 ")

     姓名 性別  國文  英文  數學   地理  歷史
2   黃詩涵  女  59  87  65  100  75
5   鄭詩涵  女  50  51  95   63  74
10  楊欣怡  女  54  92  99   97  78

In [14]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')
#scores_df

     姓名 性別   國文   英文  數學   地理   歷史   總分    平均    排名
34  劉家豪  男   92  100  95   75   99  461  92.2   1.0
47  林柏翰  男   75  100  98   58  100  431  86.2   2.0
30  謝怡君  女   97   79  79   91   83  429  85.8   3.0
26  蔡欣怡  女   81   78  87   97   81  424  84.8   4.0
41  陳柏翰  男   97   77  65   88   93  420  84.0   5.0
10  楊欣怡  女   54   92  99   97   78  420  84.0   5.0
43  陳怡君  女   85   83  77   91   84  420  84.0   5.0
23  王志明  男   93   86  98   62   76  415  83.0   8.0
21  邱柏翰  男   59   94  81   86   94  414  82.8   9.0
16  曾俊傑  男   84   67  91   73   96  411  82.2  10.0
24  王怡君  女   93   76  56   97   85  407  81.4  11.0
28  林冠宇  男   75   91  80   80   78  404  80.8  12.0
12  許詩涵  女   98   57  74   88   84  401  80.2  13.0
6   鄭怡君  女   65   94  85   91   64  399  79.8  14.0
20  許怡君  女   75   97  80   60   86  398  79.6  15.0
33  黃柏翰  男   76   63  85   74   96  394  78.8  16.0
46  賴俊傑  男   87   81  79   53   94  394  78.8  16.0
37  楊柏翰  男   67   94  88   59   80  388  77.6  18.0
11  吳冠宇  男   96   50  60   99   83  388  77.6  18.0
22  蔡志明  男   60   99  97   74   58  388  77.6  18.0
35  徐怡君  女   97   70  55   81   83  386  77.2  21.0
2   黃詩涵  女   59   87  65  100   75  386  77.2  21.0
44  張怡君  女   78   53  91   95   68  385  77.0  23.0
38  許柏翰  男   95   90  80   66   54  385  77.0  23.0
19  邱佳蓉  女   71   73  69   96   72  381  76.2  25.0
40  廖怡君  女   94   52  63   74   98  381  76.2  25.0
32  謝柏翰  男   86   86  54   70   84  380  76.0  27.0
49  邱欣怡  女   65   97  95   65   57  379  75.8  28.0
8   李柏翰  男   87   98  73   61   59  378  75.6  29.0
31  曾志明  男   92   80  59   83   64  378  75.6  29.0
36  曾柏翰  男   87   76  65   70   79  377  75.4  31.0
15  許冠宇  男  100   69  77   59   71  376  75.2  32.0
48  劉志明  男   84   71  60   86   73  374  74.8  33.0
18  鄭冠宇  男   85   57  87   74   71  374  74.8  33.0
1   劉怡君  女   69   54  91   95   64  373  74.6  35.0
45  李雅婷  女   91   80  65   81   52  369  73.8  36.0
42  劉詩涵  女   68   90  72   76   63  369  73.8  36.0
9   賴怡君  女   99   64  64   71   68  366  73.2  38.0
39  廖冠宇  男   54   97  66   57   92  366  73.2  38.0
50  曾家豪  男   75   61  86   51   83  356  71.2  40.0
14  張詩涵  女   66   60  67   64   99  356  71.2  40.0
25  洪冠宇  男   62   69  77   77   67  352  70.4  42.0
29  楊雅婷  女   62   50  51   88   88  339  67.8  43.0
7   蔡詩涵  女   80   63  69   53   69  334  66.8  44.0
5   鄭詩涵  女   50   51  95   63   74  333  66.6  45.0
4   王家豪  男   50   66  79   73   58  326  65.2  46.0
13  廖志明  男   59   82  59   59   64  323  64.6  47.0
17  張志明  男   68   63  75   57   53  316  63.2  48.0
3   郭柏翰  男   60   69  59   68   58  314  62.8  49.0
27  洪柏翰  男   52   61  67   51   81  312  62.4  50.0